// flow-typed signature: c2e55053c85c10943e9f90ef2c64ae06
// flow-typed version: <<STUB>>/uigradients_v^0.2.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uigradients'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uigradients' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uigradients/dist/uigradients.es' {
  declare module.exports: any;
}

declare module 'uigradients/dist/uigradients' {
  declare module.exports: any;
}

declare module 'uigradients/dist/uigradients.min' {
  declare module.exports: any;
}

declare module 'uigradients/lib/components/gradient' {
  declare module.exports: any;
}

declare module 'uigradients/lib/generator' {
  declare module.exports: any;
}

declare module 'uigradients/lib/gradients' {
  declare module.exports: any;
}

declare module 'uigradients/lib/index' {
  declare module.exports: any;
}

declare module 'uigradients/src/components/gradient' {
  declare module.exports: any;
}

declare module 'uigradients/src/generator' {
  declare module.exports: any;
}

declare module 'uigradients/src/gradients' {
  declare module.exports: any;
}

declare module 'uigradients/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uigradients/dist/uigradients.es.js' {
  declare module.exports: $Exports<'uigradients/dist/uigradients.es'>;
}
declare module 'uigradients/dist/uigradients.js' {
  declare module.exports: $Exports<'uigradients/dist/uigradients'>;
}
declare module 'uigradients/dist/uigradients.min.js' {
  declare module.exports: $Exports<'uigradients/dist/uigradients.min'>;
}
declare module 'uigradients/lib/components/gradient.js' {
  declare module.exports: $Exports<'uigradients/lib/components/gradient'>;
}
declare module 'uigradients/lib/generator.js' {
  declare module.exports: $Exports<'uigradients/lib/generator'>;
}
declare module 'uigradients/lib/gradients.js' {
  declare module.exports: $Exports<'uigradients/lib/gradients'>;
}
declare module 'uigradients/lib/index.js' {
  declare module.exports: $Exports<'uigradients/lib/index'>;
}
declare module 'uigradients/src/components/gradient.js' {
  declare module.exports: $Exports<'uigradients/src/components/gradient'>;
}
declare module 'uigradients/src/generator.js' {
  declare module.exports: $Exports<'uigradients/src/generator'>;
}
declare module 'uigradients/src/gradients.js' {
  declare module.exports: $Exports<'uigradients/src/gradients'>;
}
declare module 'uigradients/src/index.js' {
  declare module.exports: $Exports<'uigradients/src/index'>;
}
